site_name: "MeterSphere 文档"
site_url: "https://metersphere.io"
site_description: "Document"
site_author: "MeterSphere 项目组"
google_analytics: ['UA-147297392-7', 'metersphere.io']

repo_name: "metersphere/metersphere"
repo_url: "https://github.com/metersphere/metersphere"

edit_uri: https://github.com/metersphere/docs/edit/master/docs/
theme:
    name: "material"
    logo: "img/logo-white.png"
    favicon: "img/facio.ico"
    language: "zh"
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    palette:
        - scheme: default
          accent: deep purple
          toggle:
              icon: material/weather-night
              name: 切换为浅色模式
        - scheme: slate
          accent: deep purple
          toggle:
              icon: material/weather-sunny
              name: 切换为深色模式
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.indexes
        - navigation.top
        - search.suggest
        - search.highlight
        - search.share
        - header.autohide
    custom_dir: "theme"
nav:
    - 项目介绍: index.md
    - 快速开始:
          - 一键部署: quick_start/quick_start.md
          - 创建项目: quick_start/create_project.md
          - 使用测试跟踪: quick_start/test_track.md
          - 使用接口测试: quick_start/api_test.md
          - 使用 UI 测试: quick_start/ui_test.md
          - 使用性能测试: quick_start/load_test.md
    - 系统架构: system_arch.md
    - 安装部署:
          - 网络端口要求: installation/network_port.md
          - Linux 单机部署:
                - 在线安装: installation/online_installation.md
                - 在线升级: installation/online_upgrade.md
                - 离线安装: installation/offline_installation.md                
                - 离线升级: installation/offline_upgrade.md
          - Windows 单机部署: installation/offline_installation_windows.md
          - MacOS 单机部署: installation/offline_installation_mac.md
          - Kubernetes 部署: installation/kubernetes_installation.md
          - MeterSphere 分布式部署:
                - 整体部署规划: installation/pre_work.md
                - 部署Kafka集群: installation/build_kafka.md
                - 部署Data-Streaming集群: installation/build_data_streaming.md
                - 部署Node-Controller集群: installation/build_node_controller.md
          - 数据备份与还原: installation/backup_data.md
          - 命令行工具: installation/cli.md
    - 用户手册:
          - 通用功能: user_manual/general.md
          - 我的工作台:
                - 我的仪表盘: user_manual/my_desk/dashboard.md
                - 我的待办: user_manual/my_desk/todo.md
                - 我的关注: user_manual/my_desk/attention.md
                - 我创建的: user_manual/my_desk/created.md
          - 测试跟踪:
                - 概述: user_manual/test_track/intro.md
                - 首页: user_manual/test_track/home.md
                - 功能用例:
                  - 模块树管理: user_manual/test_track/test_case/test_case_module.md
                  - 用例管理: user_manual/test_track/test_case/test_case.md
                  - 公共用例库: user_manual/test_track/test_case/public_test_case.md
                - 用例评审: user_manual/test_track/test_case_review.md
                - 测试计划:
                    - 计划列表: user_manual/test_track/test_plan/test_plan_list.md
                    - 管理计划: user_manual/test_track/test_plan/test_plan_manage.md
                    - 批量操作: user_manual/test_track/test_plan/test_plan_batch.md
                - 缺陷管理: user_manual/test_track/test_defect.md
                - 报告: user_manual/test_track/test_report.md
          - 接口测试:
                - 概述: user_manual/api_test/intro.md
                - 首页: user_manual/api_test/home.md
                - 接口定义: user_manual/api_test/api_definition.md
                - 接口自动化: user_manual/api_test/api_automation.md
                - 接口测试报告: user_manual/api_test/test_report.md
                - 接口用例操作: user_manual/api_test/api_step.md
                - 接口场景编排: user_manual/api_test/api_scenario.md
                - 内置函数: user_manual/api_test/functions.md
          - UI 测试:
                - 概述: user_manual/ui_test/intro.md
                - 元素库: user_manual/ui_test/ui_element_store.md
                - UI 自动化: user_manual/ui_test/ui_automation.md
                - 测试报告: user_manual/ui_test/ui_test_report.md  
          - 性能测试:
                - 概述: user_manual/load_test/intro.md
                - 性能测试: user_manual/load_test/load_test.md
                - 性能测试报告: user_manual/load_test/test_report.md
          - 报表统计:
                - 项目报表: user_manual/report_statistics/project_statistics.md
                - 项目报告: user_manual/report_statistics/report.md
          - 项目设置:
                - 项目信息: user_manual/project_management/project_info.md
                - 项目成员: user_manual/project_management/project_user.md
                - 用户组与权限: user_manual/project_management/usergroup_permission.md
                - 项目环境: user_manual/project_management/project_environment.md
                - 文件管理: user_manual/project_management/file_management.md
                - 误报库: user_manual/project_management/false_library.md
                - 模版管理: user_manual/project_management/template_management.md
                - 消息设置: user_manual/project_management/notice_management.md
                - 操作日志: user_manual/project_management/operation_log.md
                - 版本管理: user_manual/project_management/version management.md
                - 应用管理: user_manual/project_management/application_management.md
                - 自定义代码片段: user_manual/project_management/customcode_snippets.md
          - 系统设置:
              - 概述: user_manual/system_management/intro.md
              - 系统: user_manual/system_management/system.md
              - 工作空间: user_manual/system_management/workspace.md
          - 插件使用教程:
              - 浏览器录制插件: user_manual/plugin_use/chrome_plugin.md
              - Jenkins 插件: user_manual/plugin_use/jenkins_plugin.md
              - IDEA 插件: user_manual/plugin_use/idea_plugin.md
              - Selenium IDE 插件: user_manual/plugin_use/selenium_ide_plugin.md
              - 接口测试插件: user_manual/plugin_use/api_test_plugin.md
              - 服务集成插件: user_manual/plugin_use/service_integration_plugin.md
    - 使用教程: tutorial/use_tutorial.md
    - 教学视频: teach_video/video_index.md
    - 常见问题:
          - 安装部署相关: faq/installation.md
          - 测试跟踪相关: faq/test_track.md
          - 接口测试相关: faq/api_test.md
          - UI 测试相关: faq/ui_test.md
          - 性能测试相关: faq/load_test.md
          - 报表统计相关: faq/report_statistics.md
          - 系统设置相关: faq/system_management.md
          - 服务集成相关: faq/service_integration.md
          - 企业版相关: faq/enterprise.md
    - 开发文档:
          - 开发环境搭建: dev_manual.md
          - 接口自动化插件开发示例: automation_plugin_dev.md
    - 用户案例: case_studies/user_cases.md
    - 更新日志: about/changelog.md
    - 安全公告: about/security_bulletins.md
    - 联系我们: about/contact.md

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: True
          linenums: False
    - toc:
          permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.superfences
    - pymdownx.progressbar
    - lightgallery

extra_css:
    - css/extra.css

copyright: Copyright &copy; 2014-2023 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>

plugins:
    - search:
        lang:
          - en
          - ja
        separator: '[\s\-\.]+'

extra:
    version:
        provider: mike
    analytics:
        provider: google
        property: UA-147297392-7
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/metersphere
        - icon: fontawesome/solid/envelope
          link: mailto:support@fit2cloud.com
        - icon: fontawesome/solid/phone
          link: tel://400-052-0755
